create table users (
    id serial primary key,
    auth0_id varchar not null,
    email varchar not null,
    profile_name text not null,
    picture text not null
);

alter table users add column admin bool default false;

update users 
set admin = true
where auth0_id = 'github|39601915';

create table products (
    id serial primary key,
    type varchar not null,
    name varchar not null,
    description varchar not null,
    image_url text not null,
    price int not null
);

create table orders (
    id serial primary key,
    name varchar not null,
    shipping_address text not null, 
    city varchar not null,
    state_name text not null,
    zipcode int not null,
    stamp date default now(),
    user_id int references users(id)
);

create table line_items (
    id serial primary key,
    order_id int references orders(id),
    product_id int references products(id)
);

insert into products (type, name, description, image_url, price)
values
('wakeboard', 'Lunchtray 2019 Hyperlite', 'More than 2 years of testing and exploration have gone into the Lunchtray, our newest deck to join Hyperlite''s Cable Collective. Mastermind shaper Aaron Stumpf, who brought us the Union, has engineered flex zones into the tip and tail so wakeboarders can press away while the flex under foot remains flawless. While pressing, the tip and tail are reinforced with laminate to laminate urethane for ultimate durability. Enjoy a slightly beveled edge at 10 degrees for forgiveness and the hourglass base tunnel for a softer landing. Created atop an Abrupt Continuous Rocker, banded with Urethane Sidewalls and a look like no other, the Lunchtray is sure to be a new favorite at the park.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-lunchtray1.png&w=600&h=600&zc=2', 560),
('wakeboard', '#Hashtag 2019 Hyperlite', 'NICK DAVIES SIGNATURE MODEL: Nick Davies and Aaron Stumpf deliver again with Nick''s new Hashtag Cable Wakeboard. With more surface area, thanks to a wider profile and blunt tip and tail shape, the Hashtag supports the biggest air tricks. Tip to tail base channels increase the Hashtag''s edging ability and the exit tunnel concave delivers a solid feel on pipe rails. A refined Airstick Core combined with High Density Flex Zones in the tip and tail provides the perfect blend of flex with minimal swing weight. Nick prefers our Abrupt Continuous Rocker, for a smooth ride and locked in presses. Ride it, share it and tag it as you continue to progress your Wakeboarding.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-hashtag1.png&w=600&h=600&zc=2', 560),
('wakeboard', 'Jam 2019 Hyperlite', 'Overhauled for 2019, the Jam is re-shaped with a thinner overall profile from tip to tail. This provides the full flex characteristics cherished by today’s park riders. The new profile allows our Woodlite Core to perform with maximum efficiency. Wrapped with a 360 degree Urethane Sidewall provides a flexy feel and delivers protection going up against the most challenging rails and kickers in your favorite park.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-jam1.png&w=600&h=600&zc=2', 530),
('wakeboard', 'Union 2019 Hyperlite', 'The Union is tested, certified and celebrated by the entire team. Introducing a new shape worthy of the Union name, certifiably legit! The Union puts a twist on the new Wishbone shape beginning with its Woodlite Flex Construction. The power press rocker allows riders to easily lock into defined presses and the tip and tail concave comes in handy on pipe features. Unique to the Union is the finless feature; Aaron designed this deck for hours of endless fun at your home park. Featuring our fully wrapped ABS sidewall and sintered enduro base you can count on the Union for multiple seasons.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-union1.png&w=600&h=600&zc=2', 500),
('wakeboard', 'Ripsaw 2019 Hyperlite', 'The all new Ripsaw is the fully machined E-Core deck ready for the park. Jump into the cable scene and do it in style. Hyperlite''s Ripsaw was created to get you out on the cable, a great value for a great price to last throughout the season and further down the line. The Variable Thickness Profile delivers strategic flex zones with more flex in the tip and tail and less between the bindings. Overall however, the Ripsaw is a flexy deck perfect for all ability levels. Molded into the shape are Full Length Center Channels to assist with tracking on approach to features and kickers. ABS Sidewalls molded into the perimeter and a Sintered Base will take the abuse dished out by riders pushing their limits.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-ripsaw1.png&w=600&h=600&zc=2', 420),
('wakeboard', 'Franchise 2019 Hyperlite', 'Keep the party rocking with the Franchise. Insane pop and features packed into a do everything deck. The Franchise is an innovative shape that anyone can strap into and feel at home on. The continuous rocker lays the foundation for a fast board that carves and edges with ease. The Franchise features innovative Tapered Channels that narrow at the tip and tail aligning the Dual Fin Configuration to increase the board''s edge hold on approach to the wake. The thinner profile of the board and reduced tip and tail width minimize swing weight for simple rotation on flat and inverted spins. Shaped by Greg Nelson the Franchise will provide any Wakeboarder an unforgettable ride.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-franchise1.png&w=600&h=600&zc=2', 320),
('wakeboard', 'State 2.0 2019 Hyperlite', 'Advancing your skills quicker with advanced shape technology. A complete entry level deck. Creating a shape to take riders'' skills to the next level was the goal behind the new State 2.0. Learning from other asymmetrical designs, we found that creating a shorter but more effective edge on a rider''s toe-side made hard to learn wake jumps that much easier. Once set, the smoother toe-side transition is then held by the State 2.0''s thinner profile molded-in fin, creating less drag and a better release off the top of the wake. The longer, more traditional heel-side edge compliments this asymmetrical design by allowing the natural body position of a rider to generate stability and speed into the wake without a loss of pop due to reduced surface area. The State 2.0 has been tested and proven to be the best choice for a rider looking to master the foundations of wakeboarding.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-state1.png&w=600&h=600&zc=2', 275),
('wakeboard', 'Scandal 2019 Hyperlite', 'The Scandal is shaped and constructed so ladies will get the most out of themselves and their riding at the cable. Starting with the popular Wishbone mold we''ve dialed in the flex specifically for women’s riding. Blasting off kickers, hitting your first feature or pressing the snot out of the tail, the Scandal makes it easy. The Woodlite Flex Construction and our power press rocker combined with Hyperlite''s Satin Flex deliver a ride like no other. Durability, the Scandal has it - with ABS Sidewalls and a fully Sintered Enduro Base this board will stand up to any abuse you dish out.', 'http://assets.hosports.com/image.php?src=2019/img/wakeboards-scandal1.png&w=600&h=600&zc=2', 500),
('wakeboard', 'Eclipse 2019 Liquid Force', 'How do you make a top selling park board even better? You make it livelier and more durable! The new 2019 Eclipse comes equipped with a full wood core which gives the board extra spring loaded flex and takes what was already a durable shape and makes it bullet proof. With the LF exclusive Grind Base and Liquid Rails, this is the ultimate park board for going big off kickers and pressing on rails. The Eclipse is starting to shine a whole new light on park riding. Like Daniel Grant says, “Big boards are the future”. We say big boards are now the present!', 'https://www.liquidforce.com/images/wakeboards/lineup/big/eclipse-164.jpg', 600),
('wakeboard', 'Tao 2019 Liquid Force', 'The Tao received rave reviews this past season from park riders around the world, including Daniel Grant himself… “Crazy how connected I feel to the Tao thanks to the FlexTrack™... It really works!”. The Tao is the original board that allowed him to push his riding to mind blowing levels. The TAO comes equipped with the, LF exclusive, Flex Track system that provides a level of flex and control never felt before. This feature allows you and your board to become one when pressing on rails and edging into the kicker. In addition, the unique stepped deck profile provides lively flex and increased strength through the center of the board for aggressive riding. With a wide center concave that flows perfectly into shaped channels below your feet this finless design creates ultimate control and stability. The Tao is the perfect board for the true park rider that wants to ride more aggressively than anyone at their local park.', 'https://www.liquidforce.com/images/wakeboards/lineup/big/tao-133.jpg', 550),
('wakeboard', 'Peak 2019 Liquid Force', 'If you’re looking for a board that is ready to bounce off the water, the Peak may be the board for you. Don’t take it from us, take it from Nico himself… “I personally think it has the best pop of any board out there.” Built with a full wood core for durability AND a more spring loaded flex with rebound. The unique single concave hull shape, mid body channels, and a concave beveled edge allows this board to be ridden finless and still hold a solid edge. With the LF Exclusive Liquid Rail™s and grind base, this board can take a beating on any feature. Adding to the already impressive flex pattern of this board, the FlexTrack™ system will have you more connected and in control than ever before. You won’t need to Imagine Happiness, you will Experience Happiness.', 'https://www.liquidforce.com/images/wakeboards/lineup/big/peak-138.jpg', 550),
('wakeboard', 'Magnum 2019 Liquid Force', 'The reason we all started to wakeboard in the first place was to have FUN!!! The MAGNUM, is all about FUN and having a laid-back approach to wakeboarding. With the directional rocker, this board will rip behind any sized wake! There is no need for a waist high wake because you’ll be slayshing and grabbing on this fun machine instead of trying to master your double back roll…. The Magnum features a removable tri-fin set up on the tail so you can hit the wake with ease and a single removable fin on the nose in case you need to impress your friends by riding “backwards”. The Magnum takes us all back to an easier time in our wake life and will have you smiling from ear to ear. The Fun is Unlimited!', 'https://www.liquidforce.com/images/wakeboards/lineup/big/magnum.jpg', 550),
('wakeboard', 'FLX 2019 Liquid Force', 'True Park Performance at a Great Value! The board’s all-wood core keeps it loose on the water and springy and responsive on rails. The Liquid Rail sidewalls and LF exclusive GRIND base make it ultra-durable and add to its lifespan. Whether it’s your first park board that needs to last a long time, or you’re looking for a smooth and predictable choice, the FLX will not disappoint. Hit the cable and you’ll see why the FLX is a top choice for beginners to pros alike!', 'https://www.liquidforce.com/images/wakeboards/lineup/big/flx-135.jpg', 500),
('wakeboard', 'Noodle 2019 Liquid Force', 'Sidecut, Aysemetric outline, Flex tips… this board is about as out of the box as they come. For that rider that’s not afraid to try something new, the Noodle allows you to explore the outer dimensions of your shred sesh. The soft flex along with the flex zone tips allows this board to be pressed and popped in all directions. Maximizing its flex on the rails but still to send you off the kickers. The asym outline helps connect your feet to the apex of the rail in a direct line maximizing your control over the board both heelside and toeside and the sidecut gives you the ability turn quickly and responsively. Much like the snowboard when first introduced to the world, the Noodle will revolution your way of looking at the water.', 'https://www.liquidforce.com/images/wakeboards/lineup/big/noodle-142.jpg', 550),
('wakeboard', 'Rhythm 2019 Liquid Force', 'The Rhythm is a Park riding machine featuring our durable, sintered Grind base and flex tip technology. It has a smooth concave through the center for speed and flow that feeds out the ends to a center concave slot placed between slight quad channels for superior hold. The outside edge channels give you extra hold when combined with the straighter mid-body shape. A lifted concave edge bevel keeps the board catch free while the flexible all wood CNC’d core with Liquid Rail Flex Tips livens up the feel and sensitivity on features. Add in the aggressive continuous rocker for smooth, soft landings and you have the ultimate park board.', 'https://www.liquidforce.com/images/wakeboards/lineup/big/rhythm-140.jpg', 600),
('wakeboard', 'Fury 2019 Liquid Force', 'The Fury is all about helping kids progress and improve their riding. As they grow, the boards grow with them. The 115 (not available in DREAM) has mellow 3-stage rocker with a soft edge, the 120 features a more aggressive 3-stage rocker with a subtle sharpness to the edge, and the 125 has an aggressive rocker with a sharper edge for that larger wake. The Fury and Dream will help take your groms riding to the next level.', 'https://www.liquidforce.com/images/wakeboards/lineup/big/fury-120.jpg', 400),

('waterski', 'HO Sports 2019 Syndicate Pro', 'The Syndicate PRO was built for one purpose; To achieve the most angle and hold possible at incredible speeds and the shortest line lengths for the world''s top pro skiers. The Syndicate PRO is built with a Full Carbon Jacket, a carbon fiber wrapped top and base adds even more carbon to this skis carbon fiber rich interior. This abundance of high performance aerospace carbon fiber results in a lighter, stiffer ski with more responsiveness than ever before. The Narrow Width Profile with Aggressive Tail Taper turns and rolls on edge easily to generate massive amounts of angle. It''s large bevel size in tail results in increased hold at the finish of the turn. This means high angle turns with less blowouts. The PRO''s Pre-Flexed Continuous Rockerline allows the skier to turn predictably no matter where they stand on the ski meaning you needn''t be perfectly balanced to get the PRO to turn well. Lastly, by giving the PRO a Torsionally Stiff Flex Pattern, it holds its shape in high load situations for great acceleration at the finish of the turn.', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-syndicate-pro4.png&w=600&h=600&zc=2', 1600),
('waterski', 'HO Sports 2019 Syndicate Omni', 'The Syndicate OMNI is where precision meets efficiency. Developed to enhance ski progression in the slalom course at all speeds, this hybrid-width crossover shape is built with our ultra-high performance Carbon Fiber PVC Core Construction. The Syndicate Omni''s Flex-Frame provides increased torsional flex for the maneuverable feel of a traditional ski with the added speed & stability of a wideride ski. This allows the ski to twist creating tighter turns while added width provides the stable platform skiers need. The Omni was designed with a Hybrid Waist Width, halfway between those typically found in traditional skis and those in wideride skis. This provides for smooth instinctive turns at a wide range of speeds. Clean Edge Technology reduces drag 50% by allowing water to release cleanly off the bottom of the ski. The Clean Edge bevel-less tail offered in the Omni designs, Clean Edge 3.0, produces more acceleration with less skier input. In addition, we''ve enhanced stability by maintaining more bevel between the rear foot and fin. The result is a fast moving highly efficient ski with the handling required for tight line turns. This Carbon Fiber SpeedSkin not only reduces ski drag/increases ski speed, it also reduces ski weight by 20% by eliminating the ski base graphic material.', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-syndicate-omni2.png&w=600&h=600&zc=2', 1100),
('waterski', 'HO Sports 2019 Carbon Omni', 'A resounding improvement on crossover skis, the OMNI is optimized for the skier who needs one ski to do everything. Developed for high versatility with added responsiveness, the Carbon OMNI marries high performance aggressive skiing with the efficiency essential for open water skiing. Its Carbon Construction provides tip to tail stiffness for greater acceleration and enhanced performance and higher speeds. It''s also longitudinally stiffer for the more aggressive skier who demands more horsepower and increased response in pursuit of throwing the biggest water walls. The Carbon Omni''s Flex-Frame provides increased torsional flex for the maneuverable feel of a traditional ski with the added speed & stability of a wideride ski. This allows the ski to twist creating tighter turns while added width provides the stable platform skiers need. The Omni was designed with a Hybrid Waist Width, halfway between those typically found in traditional skis and those in wideride skis. This provides for smooth instinctive turns at a wide range of speeds. Clean Edge Technology reduces drag 50% by allowing water to release cleanly off the bottom of the ski. This differs from conventional edges where water wraps around the bevel, up the sidewall and releases off the upper edge creating suction. In addition, we''ve enhanced stability by maintaining more bevel between the rear foot and fin. The result is a fast moving highly efficient ski with the handling required for tight line turns.', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-carbon-omni1.png&w=600&h=600&zc=2', 630),
('waterski', 'HO Sports 2019 Women''s Carbon Omni', 'A resounding improvement on crossover skis, the OMNI is optimized for the skier who needs one ski to do everything. Developed for high versatility with added responsiveness, the Carbon OMNI marries high performance aggressive skiing with the efficiency essential for open water skiing. Its Carbon Construction provides tip to tail stiffness for greater acceleration and enhanced performance and higher speeds. It''s also longitudinally stiffer for the more aggressive skier who demands more horsepower and increased response in pursuit of throwing the biggest water walls. The Carbon Omni''s Flex-Frame provides increased torsional flex for the maneuverable feel of a traditional ski with the added speed & stability of a wideride ski. This allows the ski to twist creating tighter turns while added width provides the stable platform skiers need. The Omni was designed with a Hybrid Waist Width, halfway between those typically found in traditional skis and those in wideride skis. This provides for smooth instinctive turns at a wide range of speeds. Clean Edge Technology reduces drag 50% by allowing water to release cleanly off the bottom of the ski. This differs from conventional edges where water wraps around the bevel, up the sidewall and releases off the upper edge creating suction. In addition, we''ve enhanced stability by maintaining more bevel between the rear foot and fin. The result is a fast moving highly efficient ski with the handling required for tight line turns.', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-carbon-womens-omni1.png&w=600&h=600&zc=2', 630),
('waterski', 'HO Sports 2019 Omni', 'A resounding improvement on crossover skis, the OMNI is optimized for the skier who needs one ski to do everything. Developed for high versatility with added responsiveness, the Carbon OMNI marries high performance aggressive skiing with the efficiency essential for open water skiing. Its Carbon Construction provides tip to tail stiffness for greater acceleration and enhanced performance and higher speeds. It''s also longitudinally stiffer for the more aggressive skier who demands more horsepower and increased response in pursuit of throwing the biggest water walls. The Carbon Omni''s Flex-Frame provides increased torsional flex for the maneuverable feel of a traditional ski with the added speed & stability of a wideride ski. This allows the ski to twist creating tighter turns while added width provides the stable platform skiers need. The Omni was designed with a Hybrid Waist Width, halfway between those typically found in traditional skis and those in wideride skis. This provides for smooth instinctive turns at a wide range of speeds. Clean Edge Technology reduces drag 50% by allowing water to release cleanly off the bottom of the ski. This differs from conventional edges where water wraps around the bevel, up the sidewall and releases off the upper edge creating suction. In addition, we''ve enhanced stability by maintaining more bevel between the rear foot and fin. The result is a fast moving highly efficient ski with the handling required for tight line turns.', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-omni1.png&w=600&h=600&zc=2', 430),
('waterski', 'HO Sports 2019 Women''s Omni', 'A resounding improvement on crossover skis, the OMNI is optimized for the skier who needs one ski to do everything. Developed for high versatility with added responsiveness, the Carbon OMNI marries high performance aggressive skiing with the efficiency essential for open water skiing. Its Carbon Construction provides tip to tail stiffness for greater acceleration and enhanced performance and higher speeds. It''s also longitudinally stiffer for the more aggressive skier who demands more horsepower and increased response in pursuit of throwing the biggest water walls. The Carbon Omni''s Flex-Frame provides increased torsional flex for the maneuverable feel of a traditional ski with the added speed & stability of a wideride ski. This allows the ski to twist creating tighter turns while added width provides the stable platform skiers need. The Omni was designed with a Hybrid Waist Width, halfway between those typically found in traditional skis and those in wideride skis. This provides for smooth instinctive turns at a wide range of speeds. Clean Edge Technology reduces drag 50% by allowing water to release cleanly off the bottom of the ski. This differs from conventional edges where water wraps around the bevel, up the sidewall and releases off the upper edge creating suction. In addition, we''ve enhanced stability by maintaining more bevel between the rear foot and fin. The result is a fast moving highly efficient ski with the handling required for tight line turns.', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-womens-omni1.png&w=600&h=600&zc=2', 430),
('waterski', 'HO Sports 2019 Hovercraft', 'With a surface area comparable to two skis combined, the Hovercraft provides get-ups easier than on a wakeboard and once up, it rips turns like a surfboard! It''s a great choice for beginners all the way to experts who want fun surf-inspired open water ski sessions. Great control and better balance in a low effort waterski that works great at low speeds. The days of tug-of-war deep water starts are over, as the Hovercraft lifts skiers out of the water like they''ve been given a helium injection. Widetrack Frame: Extra stable platform for easy deep water starts. The fuller ski outline means clear directional getups…less wobble & less spray in the face! More surface area also allows for smoother getups at slower speeds!', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-hovercraft1.png&w=600&h=600&zc=2', 400),
('waterski', 'HO Sports 2019 Women''s Hovercraft', 'With a surface area comparable to two skis combined, the Hovercraft provides get-ups easier than on a wakeboard and once up, it rips turns like a surfboard! It''s a great choice for beginners all the way to experts who want fun surf-inspired open water ski sessions. Great control and better balance in a low effort waterski that works great at low speeds. The days of tug-of-war deep water starts are over, as the Hovercraft lifts skiers out of the water like they''ve been given a helium injection. Widetrack Frame: Extra stable platform for easy deep water starts. The fuller ski outline means clear directional getups…less wobble & less spray in the face! More surface area also allows for smoother getups at slower speeds!', 'http://assets.hosports.com/image.php?src=2019/img/waterskis-womens-hovercraft1.png&w=600&h=600&zc=2', 400),
('waterski', 'O''Brien 2018 G5', 'The G5 offers competition skiers the perfect speed for the absolute top performance. Seamless transitions lead to smooth, flowing arcs, creating effortless angle and more course space than has ever been achieved in a tournament level slalom. An innovative new sidecut and perfectly matched rocker combine to form a huge and extremely forgiving “sweet spot”. The G5’s unique bottom design blends an aggressive concave for grip with subtle forebody rails, providing committed initiation while maintaining predictability. The design is so incredibly well-balanced that there is less critical impact on binding placement and fin adjustment.', 'https://obrien.com/wp-content/uploads/2017/08/2018-G5.jpg', 600),
('waterski', 'O''Brien 2018 Conquer', 'The Conquer has a unique fore-body design with greater width for an aggressive but controlled, no-compromise finish to the turn. The Conquer features a flex pattern for skiers who place a premium on stability and crosscourse angle. Our liveliest Conquer yet, the balanced, nimble feel engages the skier, delivering extreme cross-course angle and helping to set up for a controlled and outward cast in the pre-turn. Balanced, aggressive turns provide the skier with the opportunity for a secure and locked-in cut.', 'https://obrien.com/wp-content/uploads/2017/11/2018-Obrien-Skis-Conquer-Green.jpg', 550),
('waterski', 'O''Brien 2018 Prevail', 'The Prevail provides the skier the confident power and stability with the regulating characteristics and versatility availed by the polyurethane core.', 'https://obrien.com/wp-content/uploads/2017/11/2018-Obrien-Skis-Prevail-Blue.jpg', 550),
('waterski', 'O''Brien 2018 Impulse', 'Give in to your Impulse on a ski that can keep up. The Impulse features a stable shape with a softer flex for the ladies! This ski turns on a dime and is extremely forgiving.', 'https://obrien.com/wp-content/uploads/2017/11/2018-Obrien-Skis-impulse-64-turquoise.jpg', 350),

('wakesurf', 'Bucket Chucker 4.8 Hyperlite', 'The name says it all, the Bucket Chucker, will help you do just that - rip that wake to shreds in a new surf style shape. This Quad Fin Design with its vented tail channel the Bucket Chucker is designed to hold its line and carve like no other.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-bucket-chucker-481.png&w=600&h=600&zc=2', 1000),
('wakesurf', 'Bucket Chucker 5.0', 'The name says it all, the Bucket Chucker, will help you do just that - rip that wake to shreds in a new surf style shape. This Quad Fin Design with its vented tail channel the Bucket Chucker is designed to hold its line and carve like no other.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-bucket-chucker-501.png&w=600&h=600&zc=2', 1000),
('wakesurf', 'Hi-Fi Party Shark Hyperlite', 'Wake Surf fans rejoice, again Noah Flegel has pushed the limits of Wakesurfing by adding a Foot Strap Set to his Hi-Fi skim style shape. You''ve seen the videos and it''s amazing what is possible now that we''ve reinforced the deck and added inserts for foot straps. Not only is this great for advancing your skills behind the boat the Hi-Fi Party Shark is a great tool for teaching others how to wakesurf with the addition of the straps. The outstanding part is, just remove the straps and ride the deck like the Hi-Fi is meant to.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-hi-fi-party-shark-531.png&w=600&h=600&zc=2', 750),
('wakesurf', 'Quad Party Shark Hyperlite', 'Here we go, take your wakesurfing to new heights with the Quad Party Shark! Not only is this great for advancing your skills behind the boat the Quad Party Shark is a great tool for teaching others how to wakesurf with the addition of the straps. The outstanding part is, just remove the straps and ride the deck like the Quad is meant to.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-quad-party-shark-551.png&w=600&h=600&zc=2', 650),
('wakesurf', 'Automatic Hyperlite', 'The Automatic delivers a floaty surf vibe spawned from the beaches and wakes of Florida. Featuring our all new Full Carbon DuraShell Construction the Automatic looks and surfs better than the rest. DuraShell includes top and bottom carbon laminates and is finished with seamless edges eliminating flash lines, rolling smooth from edge to edge. With a Full Bamboo Base Inlay the Automatic has a lively feel when snapping turn s and popping airs. The single concave running through the midsection delivers great push in the wake. Customize your ride with four Futures Fin Boxes including 2 Flux Fins and 2 Minis for a loose or solid feel.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-automatic-471.png&w=600&h=600&zc=2', 750),
('wakesurf', 'Time Machine Hyperlite', 'This Time Machine is set for the future, of wake surfing that is! If you''ve been looking for a snappy surf style shape the Time Machine is what you''ve been waiting for. The duel concave in the tail of the Time Machine produces a fast ride and keeps you in the wave, any wave for that matter. Tested with surfers up to 220 lbs. the Time Machine is super responsive and can pop big airs with ease. Customize your ride with 4 fin settings featuring the Future Fin System. Never before seen in the world of Wakesurfing is our innovative 100% fully corked top sheet, providing the necessary grip for smashing the wave. Find the future this season with Hyperlite''s Time Machine.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-time-machine1.png&w=600&h=600&zc=2', 650),
('wakesurf', 'Shim 3.9 Hyperlite', 'The Shim is perfect for intermediate to advanced riders looking to take their skills to the next level. The Shim has a fast rocker allowing it to carry speed anywhere on the curl and its shorter profile makes it super maneuverable for rotational and air tricks. This new shape also features our all new DuraShell Technology which combines the buoyancy and feel of a high-end EPS board and the durability of a compression molded shape. Overall, this new board is the best of all worlds and one that a wakesurf enthusiast can''t pass up.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-shim-391.png&w=600&h=600&zc=2', 460),
('wakesurf', 'Shim 4.7 Hyperlite', 'The Shim is perfect for intermediate to advanced riders looking to take their skills to the next level. The Shim has a fast rocker allowing it to carry speed anywhere on the curl and its shorter profile makes it super maneuverable for rotational and air tricks. This new shape also features our all new DuraShell Technology which combines the buoyancy and feel of a high-end EPS board and the durability of a compression molded shape. Overall, this new board is the best of all worlds and one that a wakesurf enthusiast can''t pass up.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-shim-471.png&w=600&h=600&zc=2', 500),
('wakesurf', 'Good Daze Hyperlite', 'The Good Daze is perfect for intermediate to advanced riders looking to take their skills to the next level. The Good Daze has a fast rocker allowing it to carry speed anywhere on the curl and its shorter profile makes it super maneuverable for rotational and air tricks. This new shape also features our all new DuraShell Technology which combines the buoyancy and feel of a high-end EPS board and the durability of a compression molded shape. Overall, this new board is the best of all worlds and one that a wakesurf enthusiast can''t pass up.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-good-daze-531.png&w=600&h=600&zc=2', 500),
('wakesurf', 'Broadcast Hyperlite', 'The Broadcast shape provides great performance for any ability level. The Dual Concave base feature and new rocker line provide a fast responsive ride. It allows advanced riders to air out and generate speed for rotational tricks while beginner and intermediate riders can maintain the momentum and stay in the sweet spot of the curl. The Machined EVA deck pad provides maximum traction and is a feature usually reserved for the North Shore.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-broadcast-541.png&w=600&h=600&zc=2', 350),
('wakesurf', 'Landlock Hyperlite', 'The Landlock is geared for riders taking a slash for the first time, bigger riders, or just the toes on the nose mellower transitioned, tail heavy session. This fresh water creation features our softest/thickest rail with a concave top deck for that forgiving, laid-back soul turn.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-land-lock1.png&w=600&h=600&zc=2', 300),
('wakesurf', 'Gromcast Hyperlite', 'Kid''s Unite behind the boat, this time while Wakesurfing with Hyperlite''s new Gromcast. Spawned from the Broadcast series, the Gromcast is an easy to surf fun shape for all kids to enjoy. The wide profile provides the needed surface area but the Gromcast is short and easily manoeuvrable so kids can begin learning power carves and spins. Customize the ride with 3 removable fin options and relax on the cushy comfy EVA traction pad. Don''t make your groms ride a plank, get them on the Gromcast so you can sit back and watch them shred.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-gromcast1.png&w=600&h=600&zc=2', 280),
('waksurf', 'Misfit Hyperlite', 'Featuring Full Carbon DuraShell + Construction delivering the best ride on today''s wakes. With Carbon laminates on top and bottom the Misfit is bustling with energy for popping airs and quick snap turns. With the addition of the PET Foam Insert the Misfit''s durability and responsiveness is unmatched in the world of Wakesurfing. The Scott''s have also added a centerline Carbon Ringer Stringer adding rigidity. With 5 Futures Fin Boxes and 1 3-Pin Fin Placement options abound to tailor this ride to your liking.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-misfit-461.png&w=600&h=600&zc=2', 750),
('wakesurf', 'Action Hyperlite', 'The new Byerly Boards Action Surfer was spawned in the Byerly R&D Lab in Melbourne Beach Florida fitting perfectly into any surf quiver. Built with our proprietary Dura Shell Construction and EPS Core the Action is super light and very durable.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-action-461.png&w=600&h=600&zc=2', 650),
('wakesurf', 'Buzz Hyperlite', 'The Buzz was created to bridge the gap between skim and surf style boards giving you the best of both worlds. The shape was crafted by Butch to be the fastest, most maneuverable board in the Byerly surf line-up.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-buzz-461.png&w=600&h=600&zc=2', 500),
('wakesurf', 'Speedster', 'Durability and performance were the driving forces behind the new Speedster wakesurf series. Utilizing compression molded construction with the addition of our high-end RTM surf fin system, this new Butch Customs creation truly combines all our surf line has to offer.', 'http://assets.hosports.com/image.php?src=2019/img/wakesurfers-speedster-461.png&w=600&h=600&zc=2', 400),


('tube', 'HO Sports Fury', 'The Fury is a nimble D-shaped deck-style tube that puts you right in the heart of the action without breaking the bank. Riders lay on their stomachs while the Fury''s D-shape provides a stable ride with a low center of gravity. The Fury has plenty of room for one adult and is a great addition to your water sports collection. Backed by our industry leading 1 Year Warranty, the Fury will provide endless fun. Can you handle the Fury?', 'http://assets.hosports.com/image.php?src=2019/img/tubes-fury1.png&w=600&h=600&zc=2', 120),
('tube', 'HO Sports Watermelon', 'The Watermelon is a single rider, classic donut shaped tube that was designed with FUN in mind. Sit in the Watermelon with your feet in front of you or lay on your belly to put yourself in the heart of the action. The Watermelon has a full nylon cover for unmatched durability and 2 sets of handles in just the right spot for either riding style. You will enjoy ultimate comfort with soft foam handles with built in knuckle guards. The 2-Way Boston valve makes inflation and deflation a snap and you''re sure to turn heads with this cool fruit inspired design. Get yourself a Watermelon and grab your slice of the fun!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-watermelon1.png&w=600&h=600&zc=2', 100),
('tube', 'HO Sports Kiwi', 'The Kiwi is a single rider, donut shaped tube that was designed with FUN in mind. Sit in the Kiwi with your feet forward or lay on your belly to put yourself in the heart of the action. The Kiwi has 2 sets of handles in just the right spot for either riding style. You will enjoy ultimate comfort with soft foam handles with built in knuckle guards. The 2-Way Boston valve makes inflation and deflation a snap and you''re sure to turn heads with this cool fruit inspired design. Get yourself a Kiwi and grab a slice of the sweet fruity fun!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-kiwi1.png&w=600&h=600&zc=2', 100),
('tube', 'HO Sports Sunset 2', 'Traditionally, there has been very little difference between round, deck style tubes. You can buy one from any inflatable maker and they''re basically all the same. That is...until now. With the addition of HO Sports'' Shoftshell Technology, now you can tube all day without worrying about the abrasion or "tube rash" that you would get from a traditional nylon covered tube. This new technology is best thing to happen to tubes since the introduction of the nylon cover. So, grab a friend and hop aboard this 2 rider deck tube and have fun out there!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-sunset-21.png&w=600&h=600&zc=2', 150),
('tube', 'HO Sports 2G', 'HO Sports is proud to introduce the new, modular 2G towable. Grab a buddy and sit down in the ergonomic, lounge style seats OR flip the tube around and kneel on the neoprene pads while towing the tube from the opposite side...either way works great! Made from only the finest materials and backed by our 1 year limited warranty, the 2G will keep you where you want to be...on the water!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-2g1.png&w=600&h=600&zc=2', 260),
('tube', 'HO Sports Molecule 2D', 'The new Molecule 2D is like no other tube out there. Utilizing HO Sports'' Patented Sphere Technology, the front of this deck style tube is elevated off the water''s surface giving you the smoothest ride of any deck tube out there. This elevated, deck style sphere tube glides effortlessly through smooth or rough water utilizing the spheres to help absorb the shock of passing waves. The Molecule 2D not only rides well but it''s easy to climb back on from the water. With inflatable stabilizers to prevent slipping off the side, padded knee and elbow pads, soft foam handles and HO Quick Connect Tow Attachment this tube has got everything you need. Rated for 2 adults, the 2D is sure to turn heads on your lake.', 'http://assets.hosports.com/image.php?src=2019/img/tubes-molecule-2d1.png&w=600&h=600&zc=2', 460),
('tube', 'HO Sports Laguna 3', 'HO Sports is proud to introduce the new, modular Laguna 3 towable. Grab 2 of your friends and sit down in the ergonomic, couch style seats OR flip the tube around and kneel on the neoprene pads while towing the tube from the opposite side...either way works great! Made from only the finest materials and backed by our 1 year limited warranty, the Laguna 3 will keep you where you want to be...on the water!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-laguna-31.png&w=600&h=600&zc=2', 300),
('tube', 'HO Sports Viper 3', 'The Viper series brings a new element of fun and comfort to tubing. Its tapered profile puts the riders in a natural riding position and allows for easy re-boarding from the water. The Viper''s extra thick body delivers the most comfortable ride of any deck tube out there. Each rider has a spot of their own on the unique, contoured top while the new, innovative footholds provide relief when you can''t hold on much longer. Softshell technology rounds out the features list making the Viper the tube of choice for your family''s boating needs. Don''t get bit with an imitation...get yourself a Viper today.', 'http://assets.hosports.com/image.php?src=2019/img/tubes-viper-31.png&w=600&h=600&zc=2', 400),
('tube', 'HO Sports Glide 3', 'The Glide 3 is the fastest tube around! Due to its exclusive HO Convex Construction this tube has a huge riding area but a reduced contact area with the water, which makes for a super fun, quick-sliding tube. The concave riding surface also allows you to comfortably have up to three riders on the tube at a time. With the addition of HO Sports'' Softshell Tech top sheet, you can ride all day in ultimate comfort without the abrasion or "tube rash" you might get riding traditional nylon covered tubes. Backed by our industry leading 1 year warranty, the Glide 3 will keep you where you want to be...on the water!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-glide-31.png&w=600&h=600&zc=2', 400),
('tube', 'HO Sports Molecule', 'The Molecule uses the latest and most innovative technology in inflatables to perform like no other tube has ever dreamed! Its innovative, patented design isn''t just for looks. Using 3 spheres, the center platform is suspended above the water with only the spheres contacting the surface. This dramatically lowers the surface contact and drag behind the boat. The result is an extremely quick sliding, large tube that works equally well on rough or smooth water. There are tons of handles, two towing orientations, and the riding positions are only limited by your own imagination.', 'http://assets.hosports.com/image.php?src=2019/img/tubes-molecule1.png&w=600&h=600&zc=2', 650),
('tube', 'HO Sports Sunset 4', 'Traditionally, there has been very little difference between round, deck style tubes. You can buy one from any inflatable maker and they''re basically all the same. That is...until now. With the addition of HO Sports'' Shoftshell Technology, now you can tube all day without worrying about the abrasion or "tube rash" that you would get from a traditional nylon covered tube. This new technology is best thing to happen to tubes since the introduction of the nylon cover. So, grab a few friends and hop aboard this 4 rider deck tube and have fun out there!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-sunset-41.png&w=600&h=600&zc=2', 260),
('tube', 'HO Sports 4G', 'HO Sports is proud to introduce the new, modular 4G towable. Grab 3 of your friends and sit down in the ergonomic, lounge style seats OR flip the tube around and kneel on the neoprene pads while towing the tube from the opposite side...either way works great! Made from only the finest materials and backed by our 1 year limited warranty, the 4G will keep you where you want to be...on the water!', 'http://assets.hosports.com/image.php?src=2019/img/tubes-4g1.png&w=600&h=600&zc=2', 450),

('lifevest', 'HO Sports Men''s Team CGA Vest', 'HO Vests are developed and testing by the world''s top skiers. The Team vest defies convention by providing skiers the protection and flotation required by the USCG but with an unmatched non-CGA feel for flexibility in any setting. Perfect for the cross-over skier, the Team vest gives skiers the ability to wear it in a competition slalom course setting or out in the public lake/open water arena.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-team1.png&w=600&h=600&zc=2', 130),
('lifevest', 'HO Sports Women''s Team CGA Vest', 'HO Vests are developed and testing by the world''s top skiers. The Couture Vest defies convention by providing skiers the protection and flotation required by the USCG but with an unmatched non-CGA feel for flexibility in any setting. Perfect for the cross-over skier, the Couture vest gives skiers the ability to wear it in a competition slalom course setting or out in the public lake/open water arena.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-womens-team1.png&w=600&h=600&zc=2', 130),
('lifevest', 'HO Sports Men''s Code CGA Vest', 'The Code vest is a stylish, comfortable fitting vest that provides the flexibility you want for all water sports. Its independently segmented panels and glideskin treatment boost performance and durability for various body types. Just because a vest is approved by the USCG doesn''t mean it has to feel big and bulky.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-mens-code1.png&w=600&h=600&zc=2', 100),
('lifevest', 'HO Sports Men''s System CGA Vest', 'The System vest is a 4-panel, super comfortable & stylish Type III life vest that''s great to take anywhere and everywhere. Increased arm holes and segmented foam & rib panels give the System more mobility than other vests. Glideskin shoulder panels and internally hidden belt straps provide the vest with a stylish and sleek appearance.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-system1.png&w=600&h=600&zc=2', 80),
('lifevest', 'HO Sports Women''s System CGA Vest', 'The Women''s System vest is a 4-panel, super comfortable & stylish Type III life vest that''s great to take anywhere and everywhere. Increased arm holes and segmented foam & rib panels give the Women''s System more mobility than other vests. Glideskin shoulder panels and internally hidden belt straps provide the vest with a stylish and sleek appearance.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-womens-system1.png&w=600&h=600&zc=2', 80),
('lifevest', 'HO Sports Men''s Pursuit CGA Vest', 'In the Pursuit of perfection, comfort and safety we came right back to the Pursuit. Our rock solid Type III Coast Guard approved flotation device delivers maximum mobility and comfort through increased arm holes and strategically placed neoprene panels. The Pursuit''s upper panels are thinned out while the lower section contains more of the safety foam. Blind belts and asymmetrical graphics make the Pursuit a great choice for all water sports addicts.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-pursuit1.png&w=600&h=600&zc=2', 60),
('lifevest', 'HO Sports Women''s Pursuit CGA Vest', 'In the Pursuit of perfection, comfort and safety we came right back to the Women''s Pursuit. Our rock solid Type III Coast Guard approved flotation device delivers maximum mobility and comfort through increased arm holes and strategically placed neoprene panels. The lady Pursuit''s upper panels are thinned out while the lower section contains more of the safety foam while maintaining an anatomical fit for women. Blind belts and asymmetrical graphics make the Pursuit a great choice for all water sports addicts.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-womens-pursuit1.png&w=600&h=600&zc=2', 60),
('lifevest', 'HO Sports Men''s Infinite Red CGA Vest', 'The HO Infinite Life Jacket is USCG approved sized XS to 5XL. Improvements have been made by utilizing a new, softer more flexible foam, delivering more mobility and comfort. The infinite also now features a two belt, front zip design for a more comfortable fit and easier application.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-mens-infinite-blue1.png&w=600&h=600&zc=2', 40),
('lifevest', 'HO Sports Women''s Infinite Red CGA Vest', 'The HO Infinite Life Jacket is USCG approved sized XS to 5XL. Improvements have been made by utilizing a new, softer more flexible foam, delivering more mobility and comfort.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-womens-infinite1.png&w=600&h=600&zc=2', 40),
('lifevest', 'HO Sports Junior Pursuit CGA Vest', 'Junior rippers are always pushing the limits and the Teen Pursuit was designed to keep the precious ones in your life safe, secure and on top of the water. The Teen Pursuit was developed specifically for adolescent body size and shape. The Teen Pursuit is a Coast Guard Type III life vest including comfort and style at no extra charge.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-junior-pursuit1.png&w=600&h=600&zc=2', 55),
('lifevest', 'HO Sports Youth Pursuit CGA Vest', 'The HO Youth Pursuit vest is a USCGA vest designed to keep the young guns safe while on the water. Kid''s specific fit and graphics and internal belt design keep them looking good while they''re behind the boat.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-youth-pursuit1.png&w=600&h=600&zc=2', 50),
('lifevest', 'HO Sports Youth Pursuit CGA Vest', 'The HO Youth Pursuit vest is a USCGA vest designed to keep the young guns safe while on the water. Kid''s specific fit, girl specific graphics and internal belt design keep them looking good while they''re behind the boat.', 'http://assets.hosports.com/image.php?src=2019/img/waterski-vests-girls-youth-pursuit1.png&w=600&h=600&zc=2', 50),

('accessories', 'Extreme Package Rope + Handle', 'The Extreme rope and handle package features a TPU endcap for thumb traction and durability with AWSA color coded shortening loops, a standard 1" diameter grip and a 2-way weave construction. 12" Handle, Perfect for recreational skiing.', 'https://cdn.shopify.com/s/files/1/1505/2850/products/image_14.png?v=1493313833', 55),
('accessories', 'Universal Deep V Rope + Handle', 'Deep-V for easy deep water starts - keeps ski tip centered. Wakeboard style soft grip with cubic stitch pattern: Tackier when wet! Coated rope for abrasion resistance.', 'https://cdn3.volusion.com/mtyq5.eu2fn/v/vspfiles/photos/ho17-deep-v-handle-75ft-2.jpg?1462357496', 40),
('accessories', 'Universal Rope + Handle', 'The Universal Package is a one piece 75'' handle and line package with a 12" tacky rubber grip for excellent durability.', 'https://cdn.shopify.com/s/files/1/1505/2850/products/image_17.png?v=1493323879', 22),
('accessories', 'HO Hot Shot Trainer Rope', 'The Hot Shot Trainer Rope is a parent hand help rope system that completes the kid''s starter ski set. Its dual-handle mainline puts you in control of the child''s ride. Its eye-ring attachment provides the ability to attach to trainer bar for easy and stable starts.', 'https://cdn2.bigcommerce.com/server1400/fe789/products/6223/images/33135/HO-hot-shot-trainers-Rop__58230.1541631786.615.530.jpg?c=2', 20),
('accessories', 'LTD 8-Section Mainline Rope', 'This 8 Section AWSA approved Limited 8-Section tow rope is built with 80 Strand pre-stretched rope, sleeves that indicate length and detachable sections.', 'https://cdn.shopify.com/s/files/1/1505/2850/products/image_13.png?v=1493313648', 50),
('accessories', 'Syndicate Legend Inside Out Gloves', 'Who wants seams on the inside of their glove? We build the new "Inside out" legend with the seams on the outside for a seamless, comfortable fit. Built with our "BlueTec" palm material, the Legend glove is top pro Will Asher''s Glove of choice. Our revolutionary BlueTec palm material maximizes tackiness between palm and handle in wet conditions for unrivaled waterski grip. This lightweight material also allows for a comfortable, sleek fit with amazing handle feel.', 'https://cdn2.bigcommerce.com/server1400/fe789/products/7958/images/33615/HO-2019-syndicate-legend-inside-out-slalom-waterski-gloves__33544.1542292355.1280.1280.jpg?c=2', 65),
('accessories', 'HO 2019 Men''s World Cup Gloves', 'The World Cup glove has been redesigned to suit skiers who want maximum handle feel with added comfort and stitched reinforcements for added glove life. The World Cup employs a comfortable elastic fit while putting just enough soft palm material between the hand and handle to maintain a true connection many skiers desire above all else.', 'https://cdn2.bigcommerce.com/server1400/fe789/products/7090/images/27117/ho-world-cup-water-ski-glove-top__36859.1509542605.615.530.jpg?c=2', 40),
('accessories', 'Men''s Pro Grip Gloves', 'The Pro Grip glove includes all the essentials for improving your grip with less bulk and weight. Based on the platform of the ever popular 41 tail, the Pro Grip is a light weight glove with superior fit and comfort.', 'https://www.perfski.com/media/catalog/product/cache/4/image/9df78eab33525d08d6e5fb8d27136e95/1/6/166ho-46207.jpg', 30),
('accessories', 'Syndicate Angel Gloves', 'The Angel was designed with hi-end performance and comfort in mind. With a cut designed alongside the pro men''s line but specifically tailored for a woman''s hand shape, the Angel is the glove of choice for the aggressive female skier. The angel features pre-curved fingers and a heavy-duty Kevlar palm for durability and dependability.', 'https://cdn2.bigcommerce.com/server1400/fe789/products/8052/images/33617/HO-2019-syndicate-Angel-womens-inside-out-slalom-waterski-gloves__48936.1542292416.615.530.jpg?c=2', 65),
('accessories', 'HO 2019 Women''s World Cup Gloves', 'The World Cup glove has been redesigned to suit skiers who want maximum handle feel with added comfort and stitched reinforcements for added glove life. The World Cup employs a comfortable elastic fit while putting just enough soft palm material between the hand and handle to maintain a true connection many skiers desire above all else.', 'https://cdn2.bigcommerce.com/server1400/fe789/products/7091/images/27121/ho-womens-world-cup-water-ski-glove-top__96687.1509543258.615.530.jpg?c=2', 40),
('accessories', 'Women''s Pro Grip Gloves', 'The Pro Grip glove includes all the essentials for improving your grip with less bulk and weight. Based on the platform of the ever popular 41 tail, the Pro Grip is a light weight glove with superior fit and comfort.', 'https://cdn2.bigcommerce.com/server1400/fe789/products/3885/images/15791/ho_pro_grip_womens_water_ski_glove__44540.1416608178.1280.1280.jpg?c=2', 30),
('accessories', 'Waterski Flag', 'This inexpensive bright orange vinyl flag is attached to a 24" pole. It conforms to AZ, CA, CO, ID, IL, MO, NE, NM, OR, TX, UT & WA laws. Recommended everywhere for safety. Flag size: 12" x 15".', 'https://www.airhead.com/media/catalog/product/cache/3/image/9df78eab33525d08d6e5fb8d27136e95/F/-/F-1.jpg', 5);


